# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BelBankApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BelBankApp
   pod 'GoogleMaps'
   pod 'RealmSwift'
   pod 'Moya'
   pod 'Moya-ObjectMapper', '2.9'

end
